In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

LOADING THE DATASET

In [2]:
df = pd.read_csv("../data/cardekho_dataset.csv")

Data inspection starts from the next cell

In [3]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.shape

(15411, 14)

In [5]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  str
 2   brand              15411 non-null  str
 3   model              15411 non-null  str
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  str
 7   fuel_type          15411 non-null  str
 8   transmission_type  15411 non-null  str
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), str(6)
memory usage: 1.6 MB

In [7]:
df.describe()

,Unnamed: 0,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,9811.857699,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,5643.418542,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4906.500000,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9872.000000,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,14668.500000,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [8]:
df.isnull().sum(axis=0) #NO null values for any features so nothing to clean up over here

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["fuel_type"].value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [11]:
df["transmission_type"].value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [12]:
df["seller_type"].value_counts()

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [13]:
df["transmission_type"].nunique()

2

In [14]:
df["fuel_type"].nunique()

5

In [15]:
df["seller_type"].nunique()

3

From the next cell onwards, we are moving to the data clean up part

In [ ]:
df.drop(columns=["Unnamed: 0"], inplace=True) #REMOVE unnecesssary feature(column) , if i run this twice then its giving me error when i am running it for the second time bcuz  when i ran it first time , the intendend column got deleted and it didnt exist when i ran it for the second time.

In [17]:
df.head(10)

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
5,Maruti Wagon R,Maruti,Wagon R,8,35000,Individual,Petrol,Manual,18.90,998,67.10,5,350000
6,Hyundai i10,Hyundai,i10,8,40000,Dealer,Petrol,Manual,20.36,1197,78.90,5,315000
7,Maruti Wagon R,Maruti,Wagon R,3,17512,Dealer,Petrol,Manual,20.51,998,67.04,5,410000
8,Hyundai Venue,Hyundai,Venue,2,20000,Individual,Petrol,Automatic,18.15,998,118.35,5,1050000
9,Maruti Swift,Maruti,Swift,4,28321,Dealer,Petrol,Manual,16.60,1197,85.00,5,511000

In [18]:
df.isnull().sum(axis=0) #In our dataset we have 0 columns with null value so no cleanup is needed for this part hence we will move on

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(167)

In [20]:
df[df.duplicated(keep=False)].head(20)

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
25,Maruti Swift Dzire,Maruti,Swift Dzire,6,90000,Individual,Diesel,Manual,26.59,1248,74.00,5,600000
67,Honda City,Honda,City,8,70000,Individual,Petrol,Manual,16.80,1497,116.30,5,545000
159,Maruti Alto,Maruti,Alto,2,25000,Individual,Petrol,Manual,24.70,796,47.30,5,310000
197,Honda City,Honda,City,8,70000,Individual,Petrol,Manual,16.80,1497,116.30,5,545000
214,Renault KWID,Renault,KWID,4,35000,Individual,Petrol,Automatic,24.04,999,67.00,5,350000
258,Maruti Swift Dzire,Maruti,Swift Dzire,4,50000,Individual,Diesel,Manual,28.40,1248,74.02,5,680000
262,Maruti Baleno,Maruti,Baleno,2,5000,Individual,Petrol,Automatic,21.40,1197,83.10,5,686000
280,Mahindra KUV,Mahindra,KUV,5,70000,Individual,Diesel,Manual,25.32,1198,77.00,6,350000
330,Hyundai i20,Hyundai,i20,4,35000,Individual,Petrol,Manual,18.60,1197,81.83,5,550000
360,Maruti Baleno,Maruti,Baleno,2,5000,Individual,Petrol,Automatic,21.40,1197,83.10,5,686000
405,Hyundai i10,Hyundai,i10,9,64000,Individual,Petrol,Manual,20.36,1197,78.90,5,250000
441,Maruti Swift,Maruti,Swift,9,60000,Individual,Diesel,Manual,22.90,1248,74.00,5,400000
453,Hyundai Verna,Hyundai,Verna,2,15000,Individual,Petrol,Manual,17.00,1591,121.30,5,1030000
498,Maruti Wagon R,Maruti,Wagon R,13,100000,Individual,Petrol,Manual,18.90,1061,67.00,5,150000
524,Renault KWID,Renault,KWID,3,10000,Individual,Petrol,Manual,23.01,999,67.00,5,350000
651,Maruti Baleno,Maruti,Baleno,3,10000,Individual,Petrol,Automatic,21.40,1197,83.10,5,800000
767,Mercedes-Benz E-Class,Mercedes-Benz,E-Class,4,48000,Dealer,Diesel,Automatic,16.10,1950,191.70,5,3750000
944,Maruti Vitara,Maruti,Vitara,4,40000,Individual,Diesel,Manual,24.30,1248,88.50,5,720000
973,BMW 7,BMW,7,13,70000,Dealer,Petrol,Automatic,8.45,2979,321.00,5,750000
1069,Honda City,Honda,City,3,41000,Dealer,Petrol,Manual,17.40,1497,117.30,5,800000

Duplicate rows(training examples) will increase the weight for those particular examples during training which is not bad for the model , hence we will drop all the duplicates

In [21]:
print(df.shape[0])
df.drop_duplicates(inplace=True) # this will delete all the duplicate rows while only keeping their first occurance
print(df.duplicated().sum()) # to confirm that u have successfully removed those rows
print(df.shape[0]) # should be 167 less than before bcuz previously we had 167 duplicate rows

15411
0
15244

Now that we have dealt with null values of featues(columns) and duplicate training examples(rows) , we will proceed to clean up suspicious datatypes and other values

In [22]:
df.dtypes #looking below all the data types look just about right so no need to do any clean up in here

car_name                 str
brand                    str
model                    str
vehicle_age            int64
km_driven              int64
seller_type              str
fuel_type                str
transmission_type        str
mileage              float64
engine                 int64
max_power            float64
seats                  int64
selling_price          int64
dtype: object

In [23]:
df[["vehicle_age", "km_driven" , "mileage", "engine", "max_power", "seats" ,"selling_price"]].describe() #Using the describe function on all the features that have numerical values to look for extremes or invalid values(for eg: selling price or km_driven in negative or something too big to make sense)

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15244.000000,1.524400e+04,15244.000000,15244.000000,15244.000000,15244.000000,1.524400e+04
mean,6.041131,5.563958e+04,19.697333,1486.171543,100.607652,5.326161,7.747014e+05
std,3.016228,5.176630e+04,4.169307,520.419390,42.915687,0.808760,8.946761e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.590000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

Minimum value of seat feature is 0 which doesnt make sense so we will take a look at it , max km driven is 38 lakhs and max price is 3.8 crore which is also strange but 
can be valid for some extreme test cases

In [ ]:
df[df["seats"]==0] #theres 2 examples i can delete them or fill them with correct values by finding out correct values from other examples and putting them there , i choose to go with the 2nd method

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
3217,Honda City,Honda,City,18,40000,Individual,Petrol,Manual,13.00,1493,100.00,0,115000
12619,Nissan Kicks,Nissan,Kicks,2,10000,Individual,Diesel,Manual,19.39,1461,108.49,0,1154000

In [29]:
df.loc[(df["brand"] == "Honda") & (df["model"] == "City")]

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
23,Honda City,Honda,City,6,50000,Individual,Petrol,Manual,17.4,1497,117.3,5,750000
27,Honda City,Honda,City,14,77253,Dealer,Petrol,Manual,17.7,1497,78.0,5,145000
37,Honda City,Honda,City,6,31180,Dealer,Petrol,Automatic,18.0,1497,117.3,5,700000
67,Honda City,Honda,City,8,70000,Individual,Petrol,Manual,16.8,1497,116.3,5,545000
79,Honda City,Honda,City,7,69000,Dealer,Diesel,Manual,25.1,1498,98.6,5,550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15325,Honda City,Honda,City,7,220000,Dealer,Diesel,Manual,26.0,1498,98.6,5,550000
15330,Honda City,Honda,City,7,110000,Individual,Diesel,Manual,26.0,1498,98.6,5,490000
15369,Honda City,Honda,City,9,54311,Dealer,Petrol,Manual,16.8,1497,116.3,5,465000
15385,Honda City,Honda,City,10,28147,Dealer,Petrol,Manual,17.0,1497,118.0,5,500000
15410,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.0,1497,117.6,5,1200000

In [30]:
df.loc[(df["brand"] == "Nissan") & (df["model"] == "Kicks")]

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
1259,Nissan Kicks,Nissan,Kicks,1,15000,Individual,Petrol,Manual,14.23,1330,153.87,5,1000000
2485,Nissan Kicks,Nissan,Kicks,1,7500,Individual,Diesel,Manual,20.45,1461,108.50,5,850000
3111,Nissan Kicks,Nissan,Kicks,2,4000,Dealer,Petrol,Manual,14.23,1498,104.55,5,890000
4937,Nissan Kicks,Nissan,Kicks,2,40000,Individual,Diesel,Manual,19.39,1461,108.00,5,1200000
9645,Nissan Kicks,Nissan,Kicks,2,11687,Trustmark Dealer,Petrol,Manual,14.23,1498,104.55,5,880000
12619,Nissan Kicks,Nissan,Kicks,2,10000,Individual,Diesel,Manual,19.39,1461,108.49,0,1154000
13160,Nissan Kicks,Nissan,Kicks,2,10000,Individual,Petrol,Manual,14.23,1498,104.55,5,950000
14275,Nissan Kicks,Nissan,Kicks,2,6200,Individual,Diesel,Manual,19.39,1461,108.00,5,1450000

Both cars have 5 seats so we will replace examples with seats = 0 to 5

In [35]:
df.loc[3217,"seats"]=5
df.loc[12619,"seats"]=5
df["seats"].describe() #confirmation

count    15244.000000
mean         5.326817
std          0.806464
min          2.000000
25%          5.000000
50%          5.000000
75%          5.000000
max          9.000000
Name: seats, dtype: float64

In [42]:
#inspecting some more extreme values but they are necessarily wrong
print(df[df["seats"]==2])
print(df[df["km_driven"] == df["km_driven"].max()])
print(df[df["selling_price"] == df["selling_price"].max()])

                    car_name          brand    model  vehicle_age  km_driven  \
311                   BMW Z4            BMW       Z4            1       2000
8455                  BMW Z4            BMW       Z4            6      27000
10385                 BMW Z4            BMW       Z4            5      17000
11245                 BMW Z4            BMW       Z4            9      33000
11955                 BMW Z4            BMW       Z4           10      24000
12820                 BMW Z4            BMW       Z4           11       5022
13040  Mercedes-Benz E-Class  Mercedes-Benz  E-Class            9      23000

      seller_type fuel_type transmission_type  mileage  engine  max_power  \
311        Dealer    Petrol         Automatic    11.29    2998     335.00
8455       Dealer    Petrol         Automatic    10.37    2979     301.72
10385      Dealer    Petrol         Automatic    10.37    2979     301.72
11245      Dealer    Petrol         Automatic    10.37    2979     301.72
11955      Dealer    Petrol         Automatic    10.37    2979     306.00
12820      Dealer    Petrol         Automatic    10.37    2979     306.00
13040      Dealer    Petrol         Automatic    10.93    3498     272.00

       seats  selling_price
311        2        8250000
8455       2        3999000
10385      2        4800000
11245      2        3425000
11955      2        3300000
12820      2        3100000
13040      2        1996000
              car_name     brand   model  vehicle_age  km_driven seller_type  \
15409  Mahindra XUV500  Mahindra  XUV500            5    3800000      Dealer

      fuel_type transmission_type  mileage  engine  max_power  seats  \
15409    Diesel            Manual     16.0    2179      140.0      7

       selling_price
15409        1225000
               car_name    brand      model  vehicle_age  km_driven  \
3799  Ferrari GTC4Lusso  Ferrari  GTC4Lusso            2       3800

     seller_type fuel_type transmission_type  mileage  engine  max_power  \
3799      Dealer    Petrol         Automatic      4.0    3855      601.0

      seats  selling_price
3799      4       39500000

In [ ]:
#inspecting categorical values to see if anythings wrong , .unique() gives us the different values that exist in the dataset
print(df["fuel_type"].unique()) 
print(df["seller_type"].unique())
print(df["transmission_type"].unique())
#Update : ran the cell and all the values look good & with this i am done with the Cleanup part

<StringArray>
['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric']
Length: 5, dtype: str
<StringArray>
['Individual', 'Dealer', 'Trustmark Dealer']
Length: 3, dtype: str
<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str